# nginx 이미지를 사용. 뒤에 version tag가 없으면 latest 를 사용.

FROM nginx:alpine

# Author

MAINTAINER yunbeom.kim@bespinglobal.com

# root 에 app 폴더를 생성.

RUN mkdir -p /app/fe

# working directory 고정.

WORKDIR /app/fe/

# working directory 에 dist 폴더 생성. 즉, /app/fe/dist

RUN mkdir ./dist

# host pc의 현재경로의 dist 폴더를 working directory 의 dist 폴더로 복사.

ADD ./dist ./dist

# nginx 의 default.conf 를 삭제.

RUN rm /etc/nginx/conf.d/default.conf

# host pc 의 default.conf 를 아래 경로에 복사.

COPY ./default-dev.conf /etc/nginx/conf.d/default.conf

# ENV 설정

ENV VITE_APP_SERVER=Development
ENV VITE_APP_BASE_URL_BACKEND_HOME=http://host.docker.internal:8001
ENV VITE_APP_BASE_URL_BACKEND_AUTH=http://host.docker.internal:8002
ENV VITE_APP_BASE_URL_BACKEND_MEMBER=http://host.docker.internal:8003
ENV VITE_APP_BASE_URL_FRONTEND=http://host.docker.internal

# PORT 매핑

EXPOSE 80

# container 실행 시 자동으로 실행할 command. nginx 시작.

CMD ["nginx", "-g", "daemon off;"]
