# Base Image 지정

FROM node:lts-alpine

# Info

LABEL maintainer "김윤범YunBeom Kim<yunbeom.kim@bespinglobal.com>"
LABEL title="Schedule Checker"

# 앱 디렉터리 생성

WORKDIR /app/be-home

# 앱 의존성 설치

# 가능한 경우(npm@5+) package.json과 package-lock.json을 모두 복사하기 위해

# 와일드카드를 사용

COPY package\*.json ./

# 프로덕션을 위한 코드를 빌드하는 경우

RUN npm i

# 앱 소스 추가

COPY . .

# ENV 설정

ENV BASE_URL_THIS=http://host.docker.internal:8001
ENV BASE_URL_BACKEND_HOME=http://host.docker.internal:8001
ENV BASE_URL_BACKEND_AUTH=http://host.docker.internal:8002
ENV BASE_URL_BACKEND_MEMBER=http://host.docker.internal:8003
ENV BASE_URL_FRONTEND=http://localhost

# PORT 매핑

EXPOSE 8001

# 실행

CMD ["npm", "run", "dev"]
